server:
  port: 8080
spring:
  application:
    name: email-writer
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash

